### ISSUE TITLE
Stamina System 

### ISSUE THREAD

**Issue by Thunderdojo** [Thunderdojo/ForSakenFuture#55]

**Comment by ItsaPerryBob** [comment]
Had something on going but fucked it up so cloning from my fork again and will keep looking. Were quite close to something but broke the UI..

**Comment by ItsaPerryBob** [comment]
Staminabar now working. Just decrease the increase speed and adjust the size of the staminabar. added its intended UI too.

**Comment by ItsaPerryBob** [comment]
Sent a pull request.
